#!/usr/bin/env bash
set -euo pipefail
set -x

TO_REV=$3

CLEAN=$(mktemp -d 2>/dev/null || mktemp -d -t 'clean') # This crazy workaround ensures that it will work on both Mac OS and Linux; see https://unix.stackexchange.com/questions/30091/fix-or-alternative-for-mktemp-in-os-x
trap "rm -rf \"$CLEAN\"" EXIT

mkdir "$CLEAN/src"
git archive --format=tar "$TO_REV" basalt | tar x -C "$CLEAN/src"

#NOTE: We can't exec here, because that will defeat our EXIT trap for cleaning up the temporary directory
# See https://stackoverflow.com/questions/24111981/how-can-i-achieve-bash-exit-trap-when-exec-ing-another-binary
"$CLEAN/src/basalt/git-hook-impls/update" "$@"
