#!/usr/bin/env bash
set -euo pipefail
set -x

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

export BASALT_DIR="$DIR"

#TODO: Purify this
#TODO: Make it run in a temp directory

#TODO: Lock down nixpkgs
export INSTALLER_ISO="$(echo "$(nix-build --no-out-link "$DIR/testInstaller.nix")"/iso/*.iso)"

# Necessary for UEFI
OVMF_FD="$(nix-build '<nixpkgs>' -A OVMF.fd --no-out-link)"
cp "$OVMF_FD/FV/OVMF.fd" .

qemu-img create -f qcow2 root.qcow2 10G

expect -f "$DIR/test-install.expect"
