#!/usr/bin/env bash
set -euo pipefail
set -x

REV_TO_ACTIVATE="$1"

PATH_TO_ACTIVATE="$(readlink "$GIT_DIR/builds/$REV_TO_ACTIVATE")"
ROOT="$(realpath "$GIT_DIR/../../..")"
#TODO: We need locking or something to ensure that activation occurs in the right order, at most one at a time
nix-env --store "$ROOT" -p "$ROOT/nix/var/nix/profiles/system" --set "$PATH_TO_ACTIVATE"
if [ "$ROOT" = / ] ; then
    "$PATH_TO_ACTIVATE/bin/switch-to-configuration" switch
else
    NIXOS_INSTALL_BOOTLOADER=1 nixos-enter --root "$ROOT" -- "$PATH_TO_ACTIVATE/bin/switch-to-configuration" boot
fi

# Once we've switched to it and put it in the profile, we don't need to retain it anymore
rm "$GIT_DIR/builds/$REV_TO_ACTIVATE"
