#!/usr/bin/env bash
set -euo pipefail
set -x

# Function to clean up temporary files and directories.
cleanup ()
{
    # Once we've switched to it and put it in the profile, we don't need to retain
    # the result link anymore.
    rm "$GIT_DIR/builds/$REV_TO_ACTIVATE"
}

# Ensure that cleanup always runs even if something goes wrong.
trap cleanup EXIT

REV_TO_ACTIVATE="$1"
PATH_TO_ACTIVATE="$(realpath "$GIT_DIR/builds/$REV_TO_ACTIVATE")"

switch_home_env ()
{
    "$PATH_TO_ACTIVATE/activate"
}

# switch_nixos
switch_home_env
